/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_PagesApi_Field_ResponseTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_PagesApi_Field_ResponseTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new PagesApi__Field_Response__c());
    }
}